services:
  backend_api:
    build: ./backend
    ports:
      - "8000:8000"
    # command: uvicorn main:app --host 0.0.0.0 --port 8000

  react_frontend:
    build: ./dashboard-react-frontend
    depends_on:
      - backend_api
    ports:
      - "8080:80"
