version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_api
    environment:
      - API_KEY=${API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_dashboard
    environment:
      - API_URL=http://backend:8000/predict # Comunicação via nome do serviço
      - API_KEY=${API_KEY} # Passa a mesma chave para o frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge