version: '3.8'

services:
  # Serviço do Backend (API FastAPI)
  backend:
    build: ./backend
    container_name: api_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # Serviço do Frontend (Dashboard Streamlit)
  frontend:
    build: ./frontend
    container_name: streamlit_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped
