services:
  backend:
    build:
      context: ./backend
    container_name: backend_api
    environment:
      - API_KEY=${API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app_network

  frontend:
    build:
      context: ./dashboard-react-frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    environment:
      # Dentro da rede do Docker, use o nome do serviço (backend), não localhost
      - VITE_API_URL=http://backend:8000
      - VITE_API_KEY=${API_KEY} # <--- ADICIONE ESTA LINHA
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"        # Vite (não 8501)
    volumes:
      - ./dashboard-react-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
