services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - API_KEY=${API_KEY}
      - MODEL_DIR=/app/artifacts
    volumes:
      - ./backend/artifacts:/app/artifacts   # artefatos persistentes
    ports:
      - "8000:8000"         # opcional (útil p/ /docs)
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build:
      context: ./dashboard-react-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"             # site em http://IP_VM/
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
